apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: abishekchamlagai/Kubernetes-nodejs
  name: Kubernetes-nodejs
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Kubernetes-nodejs
  template:
    metadata:
      labels:
        app: Kubernetes-nodejs
    spec:
      containers:
      - name: Kubernetes-nodejs
        image: abishekchamlagai/Kubernetes-nodejs:latest
        ports:
        - containerPort: 80
