apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: abishekchamlagai/kubernetes-nodejs
  name: kubernetes-nodejs
  namespace: web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubernetes-nodejs
  template:
    metadata:
      labels:
        app: kubernetes-nodejs
    spec:
      containers:
      - name: kubernetes-nodejs
        image: abishekchamlagai/kubernetes-nodejs:latest
        ports:
        - containerPort: 80
